development: &default
  adapter: mysql2
  database: baseball
  pool: 25
  timeout: 5000
  encoding: utf8
  username: root
  password: password

production:
  database: baseball_production
  <<: *default

test: &test
  <<: *default
  database: baseball_test
  pool: 5
  timeout: 5000
